name: koala_chat
description: An app that's going to be amazing pretty soon.
publish_to: none # Ensure we don't accidentally publish our private code! ;)
environment:
  sdk: ">=2.0.0-dev <3.0.0"
homepage: https://github.com/angel-dart/angel
dependencies:
  angel_auth: ^2.1.5
  angel_configuration: ^2.0.0 # Loads application configuration, along with support for .env files.
  angel_framework: ^2.0.0-rc.0 # The core server library.
  angel_jael: ^2.0.0 # Server-side templating engine
  angel_production: ^1.0.0-alpha
  angel_static: ^2.0.0 # Static file server
  angel_validate: ^2.0.0 # Allows for validation of input data
  angel_serialize: ^2.2.3+1
  angel_model: ^1.0.3
  angel_mongo: ^2.0.2
  angel_websocket: ^2.0.3
dev_dependencies:
  angel_serialize_generator: ^2.4.3
  build_runner: ^1.0.0
  angel_hot: ^2.0.0 # Hot-reloading support. :)
  angel_test: ^2.0.0 # Utilities for testing Angel servers.
  io: ^0.3.2
  pedantic: ^1.0.0
  test: ^1.0.0
